# Generated by Django 5.0.1 on 2025-04-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=15, unique=True)),
                ('person_name', models.CharField(max_length=255)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('death_year', models.IntegerField(blank=True, null=True)),
                ('primary_profession', models.TextField(blank=True, null=True)),
                ('known_for_title', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
