# Generated by Django 5.0.1 on 2025-04-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImportIdbmDb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('tconst', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('titleType', models.CharField(max_length=20)),
                ('primaryTitle', models.TextField()),
                ('originalTitle', models.TextField()),
                ('isAdult', models.BooleanField()),
                ('startYear', models.IntegerField(null=True)),
                ('endYear', models.IntegerField(null=True)),
                ('runtimeMinutes', models.IntegerField(null=True)),
                ('genres', models.TextField(null=True)),
            ],
        ),
    ]
